-- Merge these items into ox_inventory/data/items.lua
-- Images (optional): copy install/images/*.png into ox_inventory/web/images/

return {
    ['icebox_gold_bar'] = {
        label = 'Gold Bar',
        weight = 400,
        stack = true,
        close = true,
        description = 'Icebox gold stock.',
    },
    ['icebox_silver_bar'] = {
        label = 'Silver Bar',
        weight = 350,
        stack = true,
        close = true,
        description = 'Icebox silver stock.',
    },
    ['icebox_platinum_bar'] = {
        label = 'Platinum Bar',
        weight = 450,
        stack = true,
        close = true,
        description = 'Icebox platinum stock.',
    },
    ['icebox_diamond'] = {
        label = 'Cut Diamond',
        weight = 20,
        stack = true,
        close = true,
        description = 'Workshop stone.',
    },
    ['icebox_ruby'] = {
        label = 'Cut Ruby',
        weight = 20,
        stack = true,
        close = true,
        description = 'Workshop stone.',
    },
    ['icebox_chain_links'] = {
        label = 'Chain Links',
        weight = 80,
        stack = true,
        close = true,
        description = 'Raw links for Icebox pieces.',
    },
    ['icebox_polish'] = {
        label = 'Jewel Polish',
        weight = 40,
        stack = true,
        close = true,
        description = 'Finishing compound.',
    },
    ['icebox_tester'] = {
        label = 'Diamond Tester',
        weight = 90,
        stack = false,
        close = true,
        description = 'Read whether a worn Icebox piece is clean or snatched.',
    },
    ['icebox_rope_silver'] = {
        label = 'Silver Rope',
        weight = 180,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_figaro_gold'] = {
        label = 'Gold Figaro',
        weight = 200,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_cuban_gold'] = {
        label = 'Cuban Link Gold',
        weight = 260,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_cuban_silver'] = {
        label = 'Cuban Link Silver',
        weight = 240,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_crossed_out'] = {
        label = 'Crossed Out',
        weight = 280,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_tennis_ice'] = {
        label = 'Tennis Ice',
        weight = 220,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_medallion'] = {
        label = 'Ice Medallion',
        weight = 300,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_diamond_cuban'] = {
        label = 'Diamond Cuban',
        weight = 320,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_infinity'] = {
        label = 'Infinity Ice',
        weight = 280,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_boss'] = {
        label = 'Boss Chain',
        weight = 360,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_watch_steel'] = {
        label = 'Steel Face',
        weight = 120,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox watch. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_watch_gold'] = {
        label = 'Gold Face',
        weight = 140,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox watch. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
}
