-- Merge these items into ox_inventory/data/items.lua
-- Images: copy install/images/*.png into ox_inventory/web/images/

return {
    ['icebox_gold_bar'] = {
        label = 'Gold Bar',
        weight = 400,
        stack = true,
        close = true,
        description = 'Icebox gold stock.',
    },
    ['icebox_silver_bar'] = {
        label = 'Silver Bar',
        weight = 350,
        stack = true,
        close = true,
        description = 'Icebox silver stock.',
    },
    ['icebox_platinum_bar'] = {
        label = 'Platinum Bar',
        weight = 450,
        stack = true,
        close = true,
        description = 'Icebox platinum stock.',
    },
    ['icebox_diamond'] = {
        label = 'Cut Diamond',
        weight = 20,
        stack = true,
        close = true,
        description = 'Workshop stone.',
    },
    ['icebox_ruby'] = {
        label = 'Cut Ruby',
        weight = 20,
        stack = true,
        close = true,
        description = 'Workshop stone.',
    },
    ['icebox_chain_links'] = {
        label = 'Chain Links',
        weight = 80,
        stack = true,
        close = true,
        description = 'Raw links for Icebox pieces.',
    },
    ['icebox_polish'] = {
        label = 'Jewel Polish',
        weight = 40,
        stack = true,
        close = true,
        description = 'Finishing compound.',
    },
    ['icebox_tester'] = {
        label = 'Diamond Tester',
        weight = 90,
        stack = false,
        close = true,
        description = 'Read whether a worn Icebox piece is clean or snatched.',
    },
    ['icebox_trapper'] = {
        label = 'Trapper Chain',
        weight = 220,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_block_baby'] = {
        label = 'Block Baby',
        weight = 260,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_smokey'] = {
        label = 'Smokey',
        weight = 280,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_smokey_2'] = {
        label = 'Smokey 2',
        weight = 280,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_self_made'] = {
        label = 'Self Made',
        weight = 240,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_dumb_rich'] = {
        label = 'Dumb Rich',
        weight = 300,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_face_shot'] = {
        label = 'Face Shot',
        weight = 310,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_slime'] = {
        label = 'Slime',
        weight = 290,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_est'] = {
        label = 'EST',
        weight = 300,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_sharky'] = {
        label = 'Sharky',
        weight = 340,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_capalot'] = {
        label = 'Capalot',
        weight = 360,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox chain. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_watch_steel'] = {
        label = 'Steel Face',
        weight = 120,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox watch. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
    ['icebox_watch_gold'] = {
        label = 'Gold Face',
        weight = 140,
        stack = false,
        close = true,
        consume = 0,
        description = 'Icebox watch. Use to wear.',
        server = { export = 'dj-icebox.useChain' },
    },
}
